### ISSUE TITLE
Process keep hanging after electron app is closed (Windows)

### ISSUE THREAD

**Issue by rossicler-hostalky** [realm/realm-js#6357]
### How frequently does the bug occur?

Always

### Description

After closing a realm connection, I expect that realm kills all processes related to Realm, but instead there's always one process that keeps hanging on Windows. This doesn't seem happen on MacOS, just Windows.

### Can you reproduce the bug?

Always

### Reproduction Steps

- First thing you need to setup an electron app, which you can use [this](https://github.com/electron-react-boilerplate/electron-react-boilerplate) template for an easy setup.
- Go to `release/app` and run `yarn install realm`.
- Create any Realm App with Sync (flexible) enabled.
- Open the realm connection in the main process of Electron.
- Close the realm connection before exiting the app.
- Check task manager for hanging process.

Example code:
```
...
const app = RealmApp({ id: 'MY_REALM_ID' });

const openRealm = async () => {
    // run realm login

    const realm = await Realm.open({
        schema: [MySchema],
        sync: {
            user: app.currentUser,
            flexible: true,
        }
    });
   realm.close();
}
...
```

After the above code runs and you close the app, there will be one process from the app still running. If I don't call the function `openRealm`, all processes are closed.

I also tested without using sync, and for that everything works fine, so I'm guessing it's something related to syncSession. Example:
```
...
const openLocalRealm = async () => {

    const realm = await Realm.open({
        schema: [MySchema],
    });
   realm.close();
}
...
```
This code works as expected, no process hangs after app is closed.

### Version

11.7.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

Yes

### Platform OS and version(s)

Windows 10 Pro 22H2

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@rossicler-hostalky Thank you for reporting.

I believe that the upgrade to Realm Core v13.9.0 in Realm JS v11.7.0 could be the issue. Please try to upgrade to v11.8.0.

**Comment by rossicler-hostalky** [comment]
> @rossicler-hostalky Thank you for reporting.
> 
> I believe that the upgrade to Realm Core v13.9.0 in Realm JS v11.7.0 could be the issue. Please try to upgrade to v11.8.0.

@kneth Thanks for replying.

I tried updating realm to v11.8.0 and also v11.10.2 and no success.

Any idea of what else can I do to get this sorted?

**Comment by rossicler-hostalky** [comment]
@kneth 

I did try `pause()` before, and it wasn't enough, but I only tried on v11.7.0.

I will take a look at `wtfnode` package and try to find more information about the process hanging, once I have more insights I will share here.

**Comment by rossicler-hostalky** [comment]
@kneth 

I ran my electron app with `wtfnode` with and without calling `Realm.open`, and this is the result of both:

With:
```
[WTF Node?] open handles:
- Sockets:
  - fd -1
    - Listeners:
Unable to determine callsite for "Function". Did you require `wtfnode` at the top of your entry point?
      - connect: (anonymous) @ unknown:0
Unable to determine callsite for "Function". Did you require `wtfnode` at the top of your entry point?
      - connect: (anonymous) @ unknown:0
Unable to determine callsite for "connect". Did you require `wtfnode` at the top of your entry point?
      - connect: connect @ unknown:0
- Timers:
  - (60000 ~ 60 s) (anonymous) @ C:\Users\...\release\app\node_modules\@realm\network-transport\dist\bundle.cjs.js:78
- Others:
  - Pipe
```

Without:
```
[WTF Node?] open handles:
- Others:
  - Pipe
```
